pages: # publish Javadoc website
     tags:
         - docker
     image: eclipse-temurin:17
     stage: build
     script:
         - javadoc -d docs src/cosc202/andie/*.java
         - mkdir public
         - echo 'test' >public/test.txt
         - mv docs public/
         - ls -R public | head
         - echo 'first ten public/ files listed'
     artifacts:
        paths:
        - public
     only:
     - main

unit-test-job:
    tags:
         - docker
    image: eclipse-temurin:17
    stage: test
    script:
        - echo "Attempting to run unit tests..."
        - javac -d bin src/cosc202/andie/*.java
        - javac -d bin -classpath
            bin:lib/junit-platform-console-standalone-1.9.2.jar
            src/Tests/*.java
        - java -jar lib/junit-platform-console-standalone-1.9.2.jar -classpath
            bin --select-package Tests